#!/bin/bash
source /usr/share/initramfs-tools/hook-functions

echo "copying in $0"
for b in udevd udevadm strace; do
	copy_exec $( which $b )
done

files="
/sbin/mount
/etc/udev/links.conf
/etc/udev/udev.conf
"

for f in $files; do
	copy_exec $f
done

find /lib/udev -type f | while read file; do
	copy_exec $file
done

mods="
kernel/fs/aufs
kernel/fs/squashfs 
kernel/fs/fuse
"

for m in $mods; do
	copy_modules_dir $m
done
